
import { Currency, Transaction } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    type: 'DEPOSIT',
    amount: 100,
    currency: Currency.USDT,
    date: '2023-10-25 10:30',
    status: 'COMPLETED',
    description: 'Deposit from Binance'
  },
  {
    id: 'tx_2',
    type: 'PAYMENT',
    amount: 12.20,
    currency: Currency.USDT,
    originalAmount: 50000,
    originalCurrency: Currency.KHR,
    date: '2023-10-26 14:20',
    status: 'COMPLETED',
    description: 'KHQR Payment (50,000 KHR)',
    merchantName: 'AEON Mall'
  }
];

export const WALLET_ADDRESS = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";
export const DEMO_PIN = "123456";

export const MOCK_RATES = {
  [Currency.USDT]: {
    [Currency.USDT]: 1,
    [Currency.KHR]: 4100,
    [Currency.USD]: 1
  },
  [Currency.KHR]: {
    [Currency.USDT]: 0.0002439,
    [Currency.KHR]: 1,
    [Currency.USD]: 0.0002439
  },
  [Currency.USD]: {
    [Currency.USDT]: 1,
    [Currency.KHR]: 4100,
    [Currency.USD]: 1
  }
};

export const TRANSLATIONS = {
  en: {
    home: "Home",
    khqr: "Payment",
    assistant: "Assistant",
    earn: "Earn",
    availBalance: "Available Balance",
    approx: "Approx.",
    deposit: "Deposit USDT",
    withdraw: "Payment",
    recentTx: "Transaction History",
    scanQr: "Scan KHQR - VietQR",
    enterAmount: "Enter Amount",
    pay: "Pay Now",
    cancel: "Cancel",
    confirmPay: "Confirm Payment",
    originalAmount: "Original Amount",
    rate: "Exchange Rate",
    payWith: "Pay with USDT",
    insufficient: "Insufficient balance.",
    depositNow: "Deposit Now",
    success: "Payment Successful!",
    enterPin: "Enter Payment PIN",
    pinPlaceholder: "Enter 6-digit PIN",
    wrongPin: "Incorrect PIN",
    simulateScan: "Simulate Scan",
    assistantIntro: "Hello! I am your AI Assistant. I can help with your transaction queries.",
    assistantPlaceholder: "Ask about rates, deposit...",
    copy: "Copy",
    copied: "Copied",
    depositTitle: "Deposit USDT (TRC20)",
    simulateDeposit: "Simulate: Sent 100 USDT",
    cameraOpen: "Align QR code within frame",
    descDeposit: "Deposit USDT",
    descPayment: "KHQR Payment",
    processing: "Processing Payment...",
    invoiceTitle: "Payment Receipt",
    txnId: "Ref ID",
    status: "Status",
    service: "Service",
    time: "Time",
    payer: "From Wallet",
    done: "Done",
    txDetailTitle: "Transaction Details",
    txType: "Type",
    txAmount: "Amount",
    txDesc: "Description",
    close: "Close",
    merchant: "Merchant",
    permission: "Please enable Camera",
    uploadImage: "Upload QR Image",
    startCam: "Start Camera",
    // New Translations
    lockedTitle: "PIN Locked",
    lockedMsg: "Your account has been locked due to 5 incorrect PIN attempts. Please contact Admin to reset PIN.",
    blockedTitle: "Account Suspended",
    blockedMsg: "Your account has been suspended due to suspicious activity. Please contact Support immediately.",
    syncing: "Synchronizing Blockchain...",
    depositInstruct: "Scan QR or send USDT (TRC20) to your dedicated wallet address:",
    confirmTransfer: "Confirm Transfer",
    enterAmountHint: "Please enter the amount you sent for faster approval.",
    amountPlaceholder: "Enter amount (e.g., 100)",
    iHaveTransferred: "I Have Transferred",
    depositSent: "Deposit request sent. System will process shortly.",
    noTx: "No transactions yet",
    validAmount: "Please enter a valid amount",
    camTelegram: "Opening Telegram Camera...",
    camTelegramHint: "If popup doesn't appear, click below.",
    retry: "Retry",
    cannotScanImg: "Could not scan QR from this image.",
    supportTitle: "Telegram Support",
    yourId: "YOUR WALLET ID",
    contactSupport: "Contact Support",
    invalidKHQR: "Invalid QR Code (Not KHQR)",
    vietqrMaintenance: "Vietnam QR (VietQR) is under maintenance. Please check back later.",
    // Invoice Translations
    invoiceHeader: "TRANSACTION SUCCESSFUL",
    totalPayment: "Total Payment",
    sourceFunds: "Source of Funds",
    myWallet: "My Wallet",
    recipient: "Recipient",
    bank: "Bank Name",
    accountNumber: "Account Number",
    description: "Description",
    shareBill: "Share / Save",
    transactionNote: "Note (Optional)",
    notePlaceholder: "Enter transaction remark...",
    minPaymentKHR: "Minimum payment amount is 1,000 KHR",
    minPaymentUSD: "Minimum payment amount is 0.2 USD",
    doNotClose: "Please do not close the screen",
    // PIN Setup
    createPin: "Create New PIN",
    confirmNewPin: "Confirm New PIN",
    pinMismatch: "PINs do not match. Please try again.",
    pinSetSuccess: "PIN created successfully!",
    accountLockedTooManyAttempts: "Account locked due to 5 incorrect PIN attempts.",
    // Savings / Interest
    dailySavings: "Daily Savings",
    claimInterest: "Claim Interest",
    claimed: "Claimed",
    apy: "APY",
    interestEarned: "Pending Interest",
    claimSuccess: "Interest Claimed Successfully!",
    claimError: "Could not claim interest. Try again later.",
    nextClaim: "Next claim available tomorrow",
    tierInfo: "Interest Rate Tiers",
    askAiDetails: "Ask AI for Details",
    tierExplanation: "Your APY depends on your balance. Higher balance = Different rates.",
    range: "Balance Range",
    rateVal: "Rate",
    // Earn Tab Specific
    earnTitle: "Earn & Grow",
    totalAsset: "Total Assets",
    lockedAsset: "Locked in Savings",
    myHoldings: "My Holdings",
    savingsMarket: "Savings Market",
    subscribe: "Subscribe",
    flexible: "Flexible",
    days: "Days",
    autoRenew: "Auto-Renew",
    subscribeConfirm: "Confirm Subscription",
    subscribeMsg: "You are about to lock funds for",
    maturityDate: "Maturity Date",
    estInterest: "Est. Interest",
    insufficientForSavings: "Insufficient available balance.",
    subscriptionSuccess: "Subscription Successful!",
    active: "Active",
    redeemEarly: "Redeem Early (No Interest)",
    lockFunds: "Lock Funds",
    // Transaction Types & Statuses
    typeDeposit: "Deposit",
    typePayment: "Payment",
    typeInterest: "Interest",
    typeSavingsLock: "Savings Lock",
    typeSavingsRedeem: "Savings Redeem",
    statusCompleted: "Completed",
    statusPending: "Pending",
    statusFailed: "Failed",
    statusProcessing: "Processing",
    statusRejected: "Rejected"
  },
  vi: {
    home: "Trang chủ",
    khqr: "Thanh toán",
    assistant: "Trợ lý",
    earn: "Tích lũy",
    availBalance: "Số dư khả dụng",
    approx: "Xấp xỉ",
    deposit: "Nạp USDT",
    withdraw: "Thanh toán",
    recentTx: "Lịch sử giao dịch",
    scanQr: "Quét mã KHQR - VietQR",
    enterAmount: "Nhập số tiền",
    pay: "Thanh toán",
    cancel: "Hủy bỏ",
    confirmPay: "Xác nhận thanh toán",
    originalAmount: "Số tiền gốc",
    rate: "Tỷ giá áp dụng",
    payWith: "Thanh toán bằng USDT",
    insufficient: "Số dư không đủ.",
    depositNow: "Nạp ngay",
    success: "Thanh toán thành công!",
    enterPin: "Nhập mã PIN thanh toán",
    pinPlaceholder: "Nhập 6 số PIN",
    wrongPin: "Mã PIN không đúng",
    simulateScan: "Giả lập quét mã",
    assistantIntro: "Xin chào! Tôi là trợ lý ảo AI. Tôi có thể giải đáp thắc mắc về giao dịch của bạn.",
    assistantPlaceholder: "Hỏi về tỷ giá, cách nạp tiền...",
    copy: "Sao chép",
    copied: "Đã chép",
    depositTitle: "Nạp USDT (TRC20)",
    simulateDeposit: "Mô phỏng: Đã chuyển 100 USDT",
    cameraOpen: "Đưa mã QR vào khung hình",
    descDeposit: "Nạp USDT",
    descPayment: "Thanh toán KHQR",
    processing: "Đang xử lý giao dịch...",
    invoiceTitle: "Hóa đơn thanh toán",
    txnId: "Mã tham chiếu",
    status: "Trạng thái",
    service: "Dịch vụ",
    time: "Thời gian",
    payer: "Ví thanh toán",
    done: "Hoàn tất",
    txDetailTitle: "Chi tiết giao dịch",
    txType: "Loại giao dịch",
    txAmount: "Số tiền",
    txDesc: "Nội dung",
    close: "Đóng",
    merchant: "Người nhận",
    permission: "Vui lòng cấp quyền Camera",
    uploadImage: "Tải ảnh QR",
    startCam: "Bật Camera",
    // New Translations
    lockedTitle: "Sai PIN Quá 5 Lần",
    lockedMsg: "Tài khoản của bạn đã bị khóa tính năng thanh toán do nhập sai PIN 5 lần. Vui lòng liên hệ Admin để reset PIN.",
    blockedTitle: "Tài Khoản Bị Tạm Ngưng",
    blockedMsg: "Tài khoản của bạn đang bị tạm ngưng do phát hiện hoạt động nghi vấn. Vui lòng liên hệ CSKH.",
    syncing: "Đang đồng bộ Blockchain...",
    depositInstruct: "Quét mã hoặc gửi USDT (TRC20) vào địa chỉ ví định danh của bạn:",
    confirmTransfer: "Xác nhận chuyển tiền",
    enterAmountHint: "Vui lòng nhập số tiền bạn đã chuyển để Admin duyệt nhanh hơn.",
    amountPlaceholder: "Nhập số tiền (VD: 100)",
    iHaveTransferred: "Tôi đã chuyển tiền",
    depositSent: "Yêu cầu nạp tiền đã được gửi. Hệ thống sẽ xử lý sau ít phút.",
    noTx: "Chưa có giao dịch nào",
    validAmount: "Vui lòng nhập số tiền hợp lệ",
    camTelegram: "Đang mở Camera Telegram...",
    camTelegramHint: "Nếu popup không hiện, hãy bấm nút bên dưới.",
    retry: "Thử lại",
    cannotScanImg: "Không thể quét QR từ ảnh này.",
    supportTitle: "CSKH Telegram",
    yourId: "WALLET ID CỦA BẠN",
    contactSupport: "Liên hệ hỗ trợ",
    invalidKHQR: "Mã QR không hợp lệ (Không phải KHQR)",
    vietqrMaintenance: "QR Việt Nam (VietQR) đang bảo trì. Vui lòng quay lại sau.",
    // Invoice Translations
    invoiceHeader: "GIAO DỊCH THÀNH CÔNG",
    totalPayment: "Tổng thanh toán",
    sourceFunds: "Nguồn tiền",
    myWallet: "Ví của tôi",
    recipient: "Người nhận",
    bank: "Ngân hàng nhận",
    accountNumber: "Số tài khoản",
    description: "Nội dung",
    shareBill: "Chia sẻ / Lưu ảnh",
    transactionNote: "Ghi chú (Không bắt buộc)",
    notePlaceholder: "Nhập nội dung chuyển tiền...",
    minPaymentKHR: "Số tiền tối thiểu là 1,000 KHR",
    minPaymentUSD: "Số tiền tối thiểu là 0.2 USD",
    doNotClose: "Vui lòng không tắt màn hình",
    // PIN Setup
    createPin: "Tạo Mã PIN Mới",
    confirmNewPin: "Xác nhận Mã PIN",
    pinMismatch: "Mã PIN không khớp. Vui lòng thử lại.",
    pinSetSuccess: "Tạo mã PIN thành công!",
    accountLockedTooManyAttempts: "Tài khoản đã bị khóa do nhập sai PIN quá 5 lần.",
    // Savings / Interest
    dailySavings: "Tiền lãi chờ nhận",
    claimInterest: "Bấm nhận ngay",
    claimed: "Đã nhận",
    apy: "Lãi suất (APY)",
    interestEarned: "Tiền lãi",
    claimSuccess: "Nhận lãi thành công!",
    claimError: "Lỗi nhận lãi. Vui lòng thử lại.",
    nextClaim: "Quay lại vào ngày mai nhé",
    tierInfo: "Bảng lãi suất tiết kiệm",
    askAiDetails: "Hỏi chi tiết với AI",
    tierExplanation: "Lãi suất phụ thuộc vào số dư hiện tại của bạn.",
    range: "Mốc số dư",
    rateVal: "Lãi suất",
    // Earn Tab Specific
    earnTitle: "Tích Lũy & Đầu Tư",
    totalAsset: "Tổng Tài Sản",
    lockedAsset: "Đang Gửi Tiết Kiệm",
    myHoldings: "Gói Đang Chạy",
    savingsMarket: "Cửa Hàng Tiết Kiệm",
    subscribe: "Gửi Ngay",
    flexible: "Linh Hoạt",
    days: "Ngày",
    autoRenew: "Tự động quay vòng (Gốc+Lãi)",
    subscribeConfirm: "Xác nhận gửi",
    subscribeMsg: "Bạn đang đăng ký khóa số tiền trong",
    maturityDate: "Ngày đáo hạn",
    estInterest: "Lãi dự kiến",
    insufficientForSavings: "Số dư khả dụng không đủ.",
    subscriptionSuccess: "Đăng ký thành công!",
    active: "Đang chạy",
    redeemEarly: "Rút trước hạn (Mất lãi)",
    lockFunds: "Khóa tiền",
    // Transaction Types & Statuses
    typeDeposit: "Nạp tiền",
    typePayment: "Thanh toán",
    typeInterest: "Nhận lãi",
    typeSavingsLock: "Gửi tiết kiệm",
    typeSavingsRedeem: "Rút tiết kiệm",
    statusCompleted: "Thành công",
    statusPending: "Đang xử lý",
    statusFailed: "Thất bại",
    statusProcessing: "Đang xử lý",
    statusRejected: "Từ chối"
  },
  zh: {
    home: "首页",
    khqr: "支付",
    assistant: "助手",
    earn: "理财",
    availBalance: "可用余额",
    approx: "约",
    deposit: "充值 USDT",
    withdraw: "支付",
    recentTx: "交易记录",
    scanQr: "扫描 KHQR - VietQR",
    enterAmount: "输入金额",
    pay: "立即支付",
    cancel: "取消",
    confirmPay: "确认支付",
    originalAmount: "原始金额",
    rate: "汇率",
    payWith: "使用 USDT 支付",
    insufficient: "余额不足。",
    depositNow: "立即充值",
    success: "支付成功！",
    enterPin: "输入支付密码",
    pinPlaceholder: "输入6位密码",
    wrongPin: "密码错误",
    simulateScan: "模拟扫描",
    assistantIntro: "你好！我是 AI 助手。我可以协助您的交易疑问。",
    assistantPlaceholder: "询问汇率、充值方式...",
    copy: "复制",
    copied: "已复制",
    depositTitle: "充值 USDT (TRC20)",
    simulateDeposit: "模拟：已转账 100 USDT",
    cameraOpen: "将二维码放入框内",
    descDeposit: "充值 USDT",
    descPayment: "KHQR 支付",
    processing: "正在处理交易...",
    invoiceTitle: "支付收据",
    txnId: "交易编号",
    status: "状态",
    service: "服务",
    time: "时间",
    payer: "支付钱包",
    done: "完成",
    txDetailTitle: "交易详情",
    txType: "交易类型",
    txAmount: "金额",
    txDesc: "描述",
    close: "关闭",
    merchant: "商户",
    permission: "请启用相机",
    uploadImage: "上传二维码",
    startCam: "启动相机",
    // New Translations
    lockedTitle: "密码锁定",
    lockedMsg: "由于5次输入错误密码，支付功能已被锁定。请联系管理员重置密码。",
    blockedTitle: "账户已冻结",
    blockedMsg: "由于发现可疑活动，您的账户已被暂停。请立即联系客服。",
    syncing: "正在同步区块链...",
    depositInstruct: "扫描二维码或发送 USDT (TRC20) 到您的专属钱包地址：",
    confirmTransfer: "确认转账",
    enterAmountHint: "请输入您转账的金额以便更快审核。",
    amountPlaceholder: "输入金额 (例如: 100)",
    iHaveTransferred: "我已转账",
    depositSent: "充值请求已发送。系统稍后处理。",
    noTx: "暂无交易",
    validAmount: "请输入有效金额",
    camTelegram: "正在打开 Telegram 相机...",
    camTelegramHint: "如果弹窗未出现，请点击下方。",
    retry: "重试",
    cannotScanImg: "无法从图片中识别二维码。",
    supportTitle: "Telegram 客服",
    yourId: "您的钱包 ID",
    contactSupport: "联系客服",
    invalidKHQR: "无效二维码 (非 KHQR)",
    vietqrMaintenance: "越南二维码 (VietQR) 正在维护中。请稍后再试。",
    // Invoice Translations
    invoiceHeader: "交易成功",
    totalPayment: "支付总额",
    sourceFunds: "资金来源",
    myWallet: "我的钱包",
    recipient: "收款人",
    bank: "收款银行",
    accountNumber: "银行账号",
    description: "描述",
    shareBill: "分享 / 保存",
    transactionNote: "备注 (选填)",
    notePlaceholder: "输入转账备注...",
    minPaymentKHR: "最低支付金额 1,000 KHR",
    minPaymentUSD: "最低支付金额 0.2 USD",
    doNotClose: "请勿关闭屏幕",
    // PIN Setup
    createPin: "创建新 PIN 码",
    confirmNewPin: "确认新 PIN 码",
    pinMismatch: "PIN 码不匹配，请重试。",
    pinSetSuccess: "PIN 码创建成功！",
    accountLockedTooManyAttempts: "由于5次输入错误密码，账户已被锁定。",
    // Savings / Interest
    dailySavings: "每日收益",
    claimInterest: "领取收益",
    claimed: "已领取",
    apy: "年化 (APY)",
    interestEarned: "待领利息",
    claimSuccess: "领取成功！",
    claimError: "领取失败，请稍后重试。",
    nextClaim: "明天再来领取",
    tierInfo: "利率详情",
    askAiDetails: "询问 AI 详情",
    tierExplanation: "利率取决于您的当前余额。",
    range: "余额范围",
    rateVal: "利率",
    // Earn Tab
    earnTitle: "理财赚币",
    totalAsset: "总资产",
    lockedAsset: "定期锁定",
    myHoldings: "我的持仓",
    savingsMarket: "理财超市",
    subscribe: "申购",
    flexible: "活期",
    days: "天",
    autoRenew: "自动复投 (本+息)",
    subscribeConfirm: "确认申购",
    subscribeMsg: "您即将锁定资金",
    maturityDate: "到期日",
    estInterest: "预计利息",
    insufficientForSavings: "可用余额不足。",
    subscriptionSuccess: "申购成功！",
    active: "进行中",
    redeemEarly: "提前赎回 (扣除利息)",
    lockFunds: "锁仓",
    // Transaction Types & Statuses
    typeDeposit: "充值",
    typePayment: "支付",
    typeInterest: "利息",
    typeSavingsLock: "定期存款",
    typeSavingsRedeem: "定期赎回",
    statusCompleted: "成功",
    statusPending: "处理中",
    statusFailed: "失败",
    statusProcessing: "处理中",
    statusRejected: "已拒绝"
  },
  km: {
    home: "ទំព័រដើម",
    khqr: "បង់ប្រាក់",
    assistant: "ជំនួយការ",
    earn: "រកប្រាក់",
    availBalance: "សមតុល្យដែលអាចប្រើបាន",
    approx: "ប្រហែល",
    deposit: "ដាក់ប្រាក់ USDT",
    withdraw: "ទូទាត់",
    recentTx: "ប្រវត្តិប្រតិបត្តិការ",
    scanQr: "ស្កេន KHQR - VietQR",
    enterAmount: "បញ្ចូលចំនួនទឹកប្រាក់",
    pay: "បង់ប្រាក់ឥឡូវនេះ",
    cancel: "បោះបង់",
    confirmPay: "បញ្ជាក់ការបង់ប្រាក់",
    originalAmount: "ចំនួនដើម",
    rate: "អត្រាប្តូរប្រាក់",
    payWith: "បង់ជាមួយ USDT",
    insufficient: "សមតុល្យមិនគ្រប់គ្រាន់។",
    depositNow: "ដាក់ប្រាក់ឥឡូវនេះ",
    success: "ការបង់ប្រាក់ជោគជ័យ!",
    enterPin: "បញ្ចូលលេខកូដ PIN",
    pinPlaceholder: "បញ្ចូលលេខកូដ PIN 6 ខ្ទង់",
    wrongPin: "លេខកូដ PIN មិនត្រឹមត្រូវ",
    simulateScan: "ក្លែងធ្វើការស្កេន",
    assistantIntro: "សួស្តី! ខ្ញុំគឺជាជំនួយការ AI របស់អ្នក។ ខ្ញុំអាចជួយឆ្លើយសំណួរអំពីប្រតិបត្តិការរបស់អ្នក។",
    assistantPlaceholder: "សួរអំពីអត្រាប្តូរប្រាក់, របៀបដាក់ប្រាក់...",
    copy: "ចម្លង",
    copied: "បានចម្លង",
    depositTitle: "ដាក់ប្រាក់ USDT (TRC20)",
    simulateDeposit: "ក្លែងធ្វើ៖ បានផ្ញើ 100 USDT",
    cameraOpen: "តម្រឹម QR កូដក្នុងស៊ុម",
    descDeposit: "ដាក់ប្រាក់ USDT",
    descPayment: "ការបង់ប្រាក់ KHQR",
    processing: "កំពុងដំណើរការ...",
    invoiceTitle: "វិក្កយបត្រ",
    txnId: "លេខកូដប្រតិបត្តិការ",
    status: "ស្ថានភាព",
    service: "សេវាកម្ម",
    time: "ពេលវេលា",
    payer: "កាបូបទូទាត់",
    done: "រួចរាល់",
    txDetailTitle: "ព័ត៌មានលម្អិតប្រតិបត្តិការ",
    txType: "ប្រភេទប្រតិបត្តិការ",
    txAmount: "ចំនួនទឹកប្រាក់",
    txDesc: "បរិយាយ",
    close: "បិទ",
    merchant: "អាជីវករ",
    permission: "សូមបើកកាមេរ៉ា",
    uploadImage: "បង្ហោះរូបភាព QR",
    startCam: "បើកកាមេរ៉ា",
    // New Translations
    lockedTitle: "PIN ត្រូវបានចាក់សោ",
    lockedMsg: "គណនីរបស់អ្នកត្រូវបានចាក់សោដោយសារបញ្ចូលលេខកូដ PIN ខុស 5 ដង។ សូមទាក់ទងអ្នកគ្រប់គ្រងដើម្បីកំណត់ PIN ឡើងវិញ។",
    blockedTitle: "គណនីត្រូវបានផ្អាក",
    blockedMsg: "គណនីរបស់អ្នកត្រូវបានផ្អាកដោយសារសកម្មភាពគួរឱ្យសង្ស័យ។ សូមទាក់ទងសេវាកម្មអតិថិជន។",
    syncing: "កំពុងធ្វើសមកាលកម្ម Blockchain...",
    depositInstruct: "ស្កេន QR ឬផ្ញើ USDT (TRC20) ទៅកាន់អាសយដ្ឋានកាបូបរបស់អ្នក៖",
    confirmTransfer: "បញ្ជាក់ការផ្ទេរ",
    enterAmountHint: "សូមបញ្ចូលចំនួនទឹកប្រាក់ដែលអ្នកបានផ្ទេរ ដើម្បីឲ្យការត្រួតពិនិត្យកាន់តែលឿន។",
    amountPlaceholder: "បញ្ចូលចំនួន (ឧទាហរណ៍៖ 100)",
    iHaveTransferred: "ខ្ញុំបានផ្ទេរប្រាក់",
    depositSent: "សំណើដាក់ប្រាក់ត្រូវបានផ្ញើ។ ប្រព័ន្ធនឹងដំណើរការក្នុងពេលបន្តិចទៀត។",
    noTx: "មិនទាន់មានប្រតិបត្តិការទេ",
    validAmount: "សូមបញ្ចូលចំនួនទឹកប្រាក់ដែលត្រឹមត្រូវ",
    camTelegram: "កំពុងបើកកាមេរ៉ា Telegram...",
    camTelegramHint: "ប្រសិនបើមិនឃើញផ្ទាំងលេចឡើង សូមចុចខាងក្រោម។",
    retry: "ព្យាយាមម្តងទៀត",
    cannotScanImg: "មិនអាចស្កេន QR ពីរូបភាពនេះបានទេ។",
    supportTitle: "ជំនួយ Telegram",
    yourId: "លេខសម្គាល់កាបូបរបស់អ្នក",
    contactSupport: "ទាក់ទងជំនួយ",
    invalidKHQR: "QR Code មិនត្រឹមត្រូវ (មិនមែន KHQR)",
    vietqrMaintenance: "QR វៀតណាម (VietQR) កំពុងស្ថិតក្រោមការថែទាំ។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។",
    // Invoice Translations
    invoiceHeader: "ការបង់ប្រាក់ជោគជ័យ",
    totalPayment: "ការបង់ប្រាក់សរុប",
    sourceFunds: "ប្រភពមូលនិធិ",
    myWallet: "កាបូបរបស់ខ្ញុំ",
    recipient: "អ្នកទទួល",
    bank: "ឈ្មោះធនាគារ",
    accountNumber: "លេខគណនី",
    description: "បរិយាយ",
    shareBill: "ចែករំលែក / រក្សាទុក",
    transactionNote: "កំណត់សម្គាល់ (មិនបង្ខំ)",
    notePlaceholder: "បញ្ចូលកំណត់សម្គាល់...",
    minPaymentKHR: "ចំនួនទឹកប្រាក់អប្បបរមាគឺ 1,000 KHR",
    minPaymentUSD: "ចំនួនទឹកប្រាក់អប្បបរមាគឺ 0.2 USD",
    doNotClose: "សូមកុំបិទអេក្រង់",
    // PIN Setup
    createPin: "បង្កើតលេខកូដ PIN ថ្មី",
    confirmNewPin: "បញ្ជាក់លេខកូដ PIN ថ្មី",
    pinMismatch: "លេខកូដ PIN មិនត្រូវគ្នាទេ។ សូមព្យាយាមម្តងទៀត។",
    pinSetSuccess: "បង្កើតលេខកូដ PIN ដោយជោគជ័យ!",
    accountLockedTooManyAttempts: "គណនីត្រូវបានចាក់សោដោយសារបញ្ចូលលេខកូដ PIN ខុស 5 ដង។",
    // Savings
    dailySavings: "សន្សំប្រចាំថ្ងៃ",
    claimInterest: "ទទួលការប្រាក់",
    claimed: "បានទទួល",
    apy: "APY",
    interestEarned: "ការប្រាក់",
    claimSuccess: "ទទួលការប្រាក់ជោគជ័យ!",
    claimError: "មិនអាចទទួលការប្រាក់បានទេ។ សូមព្យាយាមម្តងទៀត។",
    nextClaim: "សូមត្រលប់មកវិញនៅថ្ងៃស្អែក",
    tierInfo: "អត្រាការប្រាក់",
    askAiDetails: "សួរ AI សម្រាប់ព័ត៌មានលម្អិត",
    tierExplanation: "អត្រាការប្រាក់អាស្រ័យលើសមតុល្យរបស់អ្នក។",
    range: "ជួរនៃសមតុល្យ",
    rateVal: "អត្រា",
    // Earn Tab
    earnTitle: "សន្សំនិងវិនិយោគ",
    totalAsset: "ទ្រព្យសកម្មសរុប",
    lockedAsset: "បានចាក់សោក្នុងការសន្សំ",
    myHoldings: "ការសន្សំរបស់ខ្ញុំ",
    savingsMarket: "ទីផ្សារសន្សំ",
    subscribe: "ចុះឈ្មោះ",
    flexible: "បត់បែន",
    days: "ថ្ងៃ",
    autoRenew: "បន្តដោយស្វ័យប្រវត្តិ",
    subscribeConfirm: "បញ្ជាក់ការចុះឈ្មោះ",
    subscribeMsg: "អ្នកហៀបនឹងចាក់សោប្រាក់សម្រាប់",
    maturityDate: "កាលបរិច្ឆេទផុតកំណត់",
    estInterest: "ការប្រាក់ប៉ាន់ស្មាន",
    insufficientForSavings: "សមតុល្យមិនគ្រប់គ្រាន់។",
    subscriptionSuccess: "ការចុះឈ្មោះជោគជ័យ!",
    active: "សកម្ម",
    redeemEarly: "ដកប្រាក់មុនកាលកំណត់",
    lockFunds: "ចាក់សោប្រាក់",
    // Transaction Types & Statuses
    typeDeposit: "ដាក់ប្រាក់",
    typePayment: "ទូទាត់",
    typeInterest: "ការប្រាក់",
    typeSavingsLock: "ការសន្សំ",
    typeSavingsRedeem: "ដកប្រាក់សន្សំ",
    statusCompleted: "ជោគជ័យ",
    statusPending: "រង់ចាំ",
    statusFailed: "បរាជ័យ",
    statusProcessing: "កំពុងដំណើរការ",
    statusRejected: "បានបដិសេធ"
  }
};
